# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import Message as google___protobuf___message___Message

from stalk_proto.models_pb2 import (
    Forecast as stalk_proto___models_pb2___Forecast,
    Ticker as stalk_proto___models_pb2___Ticker,
)

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode

class ImageFormat(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> "ImageFormat": ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List["ImageFormat"]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, "ImageFormat"]]: ...
    SVG = typing___cast("ImageFormat", 0)
    PNG = typing___cast("ImageFormat", 1)

SVG = typing___cast("ImageFormat", 0)
PNG = typing___cast("ImageFormat", 1)
global___ImageFormat = ImageFormat

class ForecastChartReq(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    format = ...  # type: global___ImageFormat
    @property
    def ticker(self) -> stalk_proto___models_pb2___Ticker: ...
    @property
    def forecast(self) -> stalk_proto___models_pb2___Forecast: ...
    def __init__(
        self,
        *,
        ticker: typing___Optional[stalk_proto___models_pb2___Ticker] = None,
        forecast: typing___Optional[stalk_proto___models_pb2___Forecast] = None,
        format: typing___Optional[global___ImageFormat] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ForecastChartReq: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ForecastChartReq: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "forecast", b"forecast", "ticker", b"ticker"
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "forecast", b"forecast", "format", b"format", "ticker", b"ticker"
        ],
    ) -> None: ...

global___ForecastChartReq = ForecastChartReq

class ChartResp(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    chart = ...  # type: builtin___bytes
    def __init__(
        self, *, chart: typing___Optional[builtin___bytes] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ChartResp: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ChartResp: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["chart", b"chart"]
    ) -> None: ...

global___ChartResp = ChartResp
