# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stalk_proto/reporter.proto

from protogen.stalk_proto import models_pb2 as stalk__proto_dot_models__pb2
from protogen.stalk_proto.google.api import (
    annotations_pb2 as stalk__proto_dot_google_dot_api_dot_annotations__pb2,
)
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="stalk_proto/reporter.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b"Z,github.com/peake100/stalkforecaster-go/proto",
    serialized_pb=b'\n\x1astalk_proto/reporter.proto\x12\x05proto\x1a(stalk_proto/google/api/annotations.proto\x1a\x18stalk_proto/models.proto"x\n\x10\x46orecastChartReq\x12\x1d\n\x06ticker\x18\x01 \x01(\x0b\x32\r.proto.Ticker\x12!\n\x08\x66orecast\x18\x02 \x01(\x0b\x32\x0f.proto.Forecast\x12"\n\x06\x66ormat\x18\x03 \x01(\x0e\x32\x12.proto.ImageFormat"\x1a\n\tChartResp\x12\r\n\x05\x63hart\x18\x01 \x01(\x0c*\x1f\n\x0bImageFormat\x12\x07\n\x03SVG\x10\x00\x12\x07\n\x03PNG\x10\x01\x32h\n\rStalkReporter\x12W\n\rForecastChart\x12\x17.proto.ForecastChartReq\x1a\x10.proto.ChartResp"\x1b\x82\xd3\xe4\x93\x02\x15"\x10/charts/forecast:\x01*B.Z,github.com/peake100/stalkforecaster-go/protob\x06proto3',
    dependencies=[
        stalk__proto_dot_google_dot_api_dot_annotations__pb2.DESCRIPTOR,
        stalk__proto_dot_models__pb2.DESCRIPTOR,
    ],
)

_IMAGEFORMAT = _descriptor.EnumDescriptor(
    name="ImageFormat",
    full_name="proto.ImageFormat",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="SVG", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PNG", index=1, number=1, serialized_options=None, type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=255,
    serialized_end=286,
)
_sym_db.RegisterEnumDescriptor(_IMAGEFORMAT)

ImageFormat = enum_type_wrapper.EnumTypeWrapper(_IMAGEFORMAT)
SVG = 0
PNG = 1


_FORECASTCHARTREQ = _descriptor.Descriptor(
    name="ForecastChartReq",
    full_name="proto.ForecastChartReq",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ticker",
            full_name="proto.ForecastChartReq.ticker",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="forecast",
            full_name="proto.ForecastChartReq.forecast",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="format",
            full_name="proto.ForecastChartReq.format",
            index=2,
            number=3,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=105,
    serialized_end=225,
)


_CHARTRESP = _descriptor.Descriptor(
    name="ChartResp",
    full_name="proto.ChartResp",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="chart",
            full_name="proto.ChartResp.chart",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=227,
    serialized_end=253,
)

_FORECASTCHARTREQ.fields_by_name[
    "ticker"
].message_type = stalk__proto_dot_models__pb2._TICKER
_FORECASTCHARTREQ.fields_by_name[
    "forecast"
].message_type = stalk__proto_dot_models__pb2._FORECAST
_FORECASTCHARTREQ.fields_by_name["format"].enum_type = _IMAGEFORMAT
DESCRIPTOR.message_types_by_name["ForecastChartReq"] = _FORECASTCHARTREQ
DESCRIPTOR.message_types_by_name["ChartResp"] = _CHARTRESP
DESCRIPTOR.enum_types_by_name["ImageFormat"] = _IMAGEFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForecastChartReq = _reflection.GeneratedProtocolMessageType(
    "ForecastChartReq",
    (_message.Message,),
    {
        "DESCRIPTOR": _FORECASTCHARTREQ,
        "__module__": "stalk_proto.reporter_pb2"
        # @@protoc_insertion_point(class_scope:proto.ForecastChartReq)
    },
)
_sym_db.RegisterMessage(ForecastChartReq)

ChartResp = _reflection.GeneratedProtocolMessageType(
    "ChartResp",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHARTRESP,
        "__module__": "stalk_proto.reporter_pb2"
        # @@protoc_insertion_point(class_scope:proto.ChartResp)
    },
)
_sym_db.RegisterMessage(ChartResp)


DESCRIPTOR._options = None

_STALKREPORTER = _descriptor.ServiceDescriptor(
    name="StalkReporter",
    full_name="proto.StalkReporter",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=288,
    serialized_end=392,
    methods=[
        _descriptor.MethodDescriptor(
            name="ForecastChart",
            full_name="proto.StalkReporter.ForecastChart",
            index=0,
            containing_service=None,
            input_type=_FORECASTCHARTREQ,
            output_type=_CHARTRESP,
            serialized_options=b'\202\323\344\223\002\025"\020/charts/forecast:\001*',
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_STALKREPORTER)

DESCRIPTOR.services_by_name["StalkReporter"] = _STALKREPORTER

# @@protoc_insertion_point(module_scope)
