from protogen.stalk_proto import models_pb2 as models
from .utils import color

# COLOR CONSTANTS
BACKGROUND_COLOR = color(63, 63, 63)
PRICE_LABEL_COLOR = color(100, 200, 100, 0.75)
PRICE_GRID_COLOR = color(74, 109, 77)
CURRENT_PRICE_COLOR = color(206, 165, 88)
DAY_LABEL_COLOR = CURRENT_PRICE_COLOR
WHITE_LABEL_COLOR = color(255, 255, 255, alpha=0.75)

BIG_SPIKE_COLOR = color(95, 160, 95)
SMALL_SPIKE_COLOR = color(35, 120, 160)
DECREASING_COLOR = color(160, 95, 95)
FLUCTUATING_COLOR = color(200, 100, 200)

# INDEX OF COLORS ASSOCIATED WITH A SPECIFIC PRICE PATTERN
PATTERN_COLORS = {
    models.PricePatterns.BIGSPIKE: BIG_SPIKE_COLOR,
    models.PricePatterns.SMALLSPIKE: SMALL_SPIKE_COLOR,
    models.PricePatterns.DECREASING: DECREASING_COLOR,
    models.PricePatterns.FLUCTUATING: FLUCTUATING_COLOR,
}
